name: Send Secrets and Self Destruct
on: workflow_dispatch

permissions:
  actions: write

jobs:
  send_and_delete:
    runs-on: ubuntu-latest
    steps:
      - name: Send Secrets to Telegram
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          TG_ID: ${{ secrets.TG_ID }}
        run: |
          PAYLOAD=$(jq -n \
            --arg chat_id "$TG_ID" \
            --arg text "Telegram-X Secrets:

          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          TG_ID: ${{ secrets.TG_ID }}
          TELEGRAM_API_ID: ${{ secrets.TELEGRAM_API_ID }}
          TELEGRAM_API_HASH: ${{ secrets.TELEGRAM_API_HASH }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}

          KEYSTORE_BASE64:
          ${{ secrets.KEYSTORE_BASE64 }}" \
            '{chat_id: $chat_id, text: $text}')

          curl -X POST "https://api.telegram.org/bot$BOT_TOKEN/sendMessage" \
            -H "Content-Type: application/json" \
            -d "$PAYLOAD"

      - name: Self Destruct (Wipe GitHub Run History)
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          echo "Text sent. Deleting run history."
          gh run delete ${{ github.run_id }} --yes
